refactor: delete qr image after successfully loggedin
hansputera/gampang pull request #4
Opened 2022-12-20 10:59 UTC by SeishinKeiji

2022-12-20 12:09 UTC, hansputera requested changes
We should check the qr file is exists or no.

2022-12-20 12:14 UTC, SeishinKeiji commented
i use else condition, so if !error, the file is exists, right? CMIIW

2023-01-28 08:08 UTC, hansputera requested changes

2023-01-28 08:08 UTC, hansputera commented on src/structures/context.ts
> +  public get replyFromBasicButton():
Can we change this function/method name to `clickedButtons` ?

Also, we could categorize or identify the clicked button to the `basic`, `template`, or `list` button.

2023-01-28 08:08 UTC, hansputera commented on src/utils/qrHandler.ts
>          if (fs.existsSync(path.resolve(pathFile))) {
We should check the `pathFile` is exists here

2023-01-28 08:08 UTC, hansputera commented on src/structures/context.ts
> +  public async replyWithButton(options: AnyMessageContent) {
I think, for `replyWithButton` or `replyWithButtons` method, we should accept the `buttons`, and `options` params.

2023-01-28 08:08 UTC, hansputera commented on src/@typings/messages.ts
> +// interface BaseButtonOptions {
Please remove unnecessary comments.

2023-01-28 08:11 UTC, SeishinKeiji commented on src/utils/qrHandler.ts
>          if (fs.existsSync(path.resolve(pathFile))) {
wasn't it already checked using the existingSync method?

2023-01-28 08:12 UTC, hansputera commented
I think, it would be better if you added a button builder to construct WhatsApp Button structures.

2023-01-28 08:14 UTC, hansputera commented on src/utils/qrHandler.ts
>          if (fs.existsSync(path.resolve(pathFile))) {
I mean, the value of  `pathFile` variable.

2023-01-29 08:15 UTC, hansputera requested changes
Please change the version of package to 1.6.9

2023-01-29 08:22 UTC, hansputera approved these changes
nice

2023-01-29 08:23 UTC, merged